"""
Batch Mode
----------
Researches multiple competitors in a single run, scores each one,
and outputs a ranked competitive landscape summary.

The output is two things:
  1. Individual briefs saved to a directory
  2. A ranked summary table (landscape.md) showing all competitors
     sorted by threat level — the thing you'd share in a strategy meeting

Usage:
    # Comma-separated list
    python batch.py --targets "Notion AI, Coda, Confluence AI, ClickUp AI"

    # From a file (one target per line)
    python batch.py --targets-file competitors.txt

    # Save all output to a directory
    python batch.py --targets "Notion AI, Coda" --output-dir briefs/

    # Skip scoring (faster, just produces briefs)
    python batch.py --targets "Notion AI, Coda" --no-score
"""

import argparse
import sys
import time
from datetime import datetime
from pathlib import Path

# ── Imports ───────────────────────────────────────────────────────────────────

try:
    import anthropic
except ImportError:
    print("❌ anthropic package not found. Run: pip install -r requirements.txt")
    sys.exit(1)

from agent import run_research_agent, format_brief
from scorer import score_brief, Scorecard, THREAT_LEVELS

# ── Threat Level Sort Order ───────────────────────────────────────────────────

THREAT_ORDER = {level: i for i, level in enumerate(THREAT_LEVELS)}
THREAT_EMOJI = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}

# ── Batch Runner ──────────────────────────────────────────────────────────────

def run_batch(
    targets: list[str],
    output_dir: Path,
    score: bool = True,
    verbose: bool = True,
) -> list[dict]:
    """
    Researches and optionally scores each target.
    Returns a list of result dicts sorted by threat level.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    results = []

    total = len(targets)

    for i, target in enumerate(targets, 1):
        if verbose:
            print(f"\n{'═' * 60}")
            print(f"  [{i}/{total}] {target}")
            print(f"{'═' * 60}")

        # ── Research ──────────────────────────────────────────────────────────
        try:
            raw_brief = run_research_agent(target=target, verbose=verbose)
        except anthropic.AuthenticationError:
            print(f"\n❌ Authentication failed. Check ANTHROPIC_API_KEY.")
            sys.exit(1)
        except Exception as e:
            print(f"\n⚠️  Research failed for '{target}': {e}. Skipping.")
            continue

        brief = format_brief(target, raw_brief)

        # Save individual brief
        safe_name = target.lower().replace(" ", "-").replace("/", "-")
        brief_path = output_dir / f"{safe_name}.md"
        brief_path.write_text(brief, encoding="utf-8")

        result = {
            "target": target,
            "brief_path": brief_path,
            "brief_text": raw_brief,
            "scorecard": None,
        }

        # ── Score ─────────────────────────────────────────────────────────────
        if score:
            try:
                scorecard = score_brief(target=target, brief_text=raw_brief, verbose=verbose)
                result["scorecard"] = scorecard

                # Append scorecard to brief file
                with brief_path.open("a", encoding="utf-8") as f:
                    f.write("\n\n---\n\n")
                    f.write(scorecard.to_markdown())

            except Exception as e:
                print(f"\n⚠️  Scoring failed for '{target}': {e}")

        results.append(result)

        # Polite pause between targets to avoid rate limits
        if i < total:
            time.sleep(2)

    # Sort by threat level (Critical first), then by composite score descending
    def sort_key(r):
        sc = r["scorecard"]
        if sc is None:
            return (99, 0)
        return (THREAT_ORDER.get(sc.overall_threat, 99), -sc.average_score())

    results.sort(key=sort_key)
    return results


# ── Landscape Summary ─────────────────────────────────────────────────────────

def build_landscape(results: list[dict], context: str = "") -> str:
    """
    Generates a ranked competitive landscape Markdown summary.
    This is the document you'd bring to a strategy meeting.
    """
    date_str = datetime.now().strftime("%B %d, %Y")
    scored = [r for r in results if r["scorecard"] is not None]
    unscored = [r for r in results if r["scorecard"] is None]

    lines = [
        "# Competitive Landscape",
        "",
        f"> **Generated by PM Research Agent** | {date_str}  ",
        f"> *{len(results)} competitors researched"
        + (f", {len(scored)} scored" if scored else "")
        + "*",
        "",
    ]

    if context:
        lines += [f"> **Context:** {context}", ""]

    lines += ["---", ""]

    # ── Ranked threat table ───────────────────────────────────────────────────
    if scored:
        lines += [
            "## Threat Rankings",
            "",
            "| Rank | Competitor | Threat | Score | Top Risk |",
            "|---|---|---|---|---|",
        ]

        for rank, r in enumerate(scored, 1):
            sc = r["scorecard"]
            emoji = THREAT_EMOJI.get(sc.overall_threat, "⚪")
            brief_link = f"[brief]({r['brief_path'].name})"
            lines.append(
                f"| {rank} | **{r['target']}** {brief_link} "
                f"| {emoji} {sc.overall_threat} "
                f"| {sc.average_score()}/10 "
                f"| {sc.top_risk} |"
            )

        lines += [""]

    # ── Dimension breakdown ───────────────────────────────────────────────────
    if scored:
        lines += [
            "## Dimension Breakdown",
            "",
            "Scores by strategic dimension across all competitors.",
            "",
            "| Competitor | Market Overlap | AI Maturity | Execution | Distribution | Resources |",
            "|---|---|---|---|---|---|",
        ]

        for r in scored:
            sc = r["scorecard"]
            s = sc.scores
            lines.append(
                f"| **{r['target']}** "
                f"| {s['market_overlap'].score}/10 "
                f"| {s['ai_maturity'].score}/10 "
                f"| {s['execution_velocity'].score}/10 "
                f"| {s['distribution_strength'].score}/10 "
                f"| {s['resource_depth'].score}/10 |"
            )

        lines += [""]

    # ── Strategic read ────────────────────────────────────────────────────────
    if scored:
        lines += ["## Strategic Summaries", ""]

        for r in scored:
            sc = r["scorecard"]
            emoji = THREAT_EMOJI.get(sc.overall_threat, "⚪")
            lines += [
                f"### {emoji} {r['target']}",
                "",
                sc.threat_summary,
                "",
                f"**Watch:** {sc.top_risk}",
                "",
            ]

    # ── Unscored ──────────────────────────────────────────────────────────────
    if unscored:
        lines += [
            "## Researched (not scored)",
            "",
        ]
        for r in unscored:
            lines.append(f"- **{r['target']}** — [{r['brief_path'].name}]({r['brief_path'].name})")
        lines += [""]

    lines += [
        "---",
        "",
        "*Generated by [PM Research Agent](https://github.com/dvmukul/pm-research-agent)*",
    ]

    return "\n".join(lines)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Batch competitive research — research and score multiple competitors at once"
    )

    target_group = parser.add_mutually_exclusive_group(required=True)
    target_group.add_argument(
        "--targets",
        help='Comma-separated list of targets (e.g. "Notion AI, Coda, Confluence AI")',
    )
    target_group.add_argument(
        "--targets-file",
        help="Path to a text file with one target per line",
    )

    parser.add_argument(
        "--output-dir",
        default="briefs",
        help="Directory to save briefs and landscape (default: briefs/)",
    )
    parser.add_argument(
        "--context",
        default="",
        help='Optional context for the landscape doc (e.g. "Q2 2025 review — IAM space")',
    )
    parser.add_argument(
        "--no-score",
        action="store_true",
        help="Skip scoring — just produce research briefs",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress per-target progress output",
    )

    args = parser.parse_args()

    # ── Parse targets ─────────────────────────────────────────────────────────
    if args.targets:
        targets = [t.strip() for t in args.targets.split(",") if t.strip()]
    else:
        targets_path = Path(args.targets_file)
        if not targets_path.exists():
            print(f"❌ File not found: {targets_path}")
            sys.exit(1)
        targets = [
            line.strip()
            for line in targets_path.read_text().splitlines()
            if line.strip() and not line.startswith("#")
        ]

    if not targets:
        print("❌ No targets found.")
        sys.exit(1)

    output_dir = Path(args.output_dir)

    print(f"\n📋 Batch run: {len(targets)} competitor(s)")
    print(f"   Targets: {', '.join(targets)}")
    print(f"   Output:  {output_dir}/")
    print(f"   Scoring: {'off' if args.no_score else 'on'}\n")

    # ── Run ───────────────────────────────────────────────────────────────────
    results = run_batch(
        targets=targets,
        output_dir=output_dir,
        score=not args.no_score,
        verbose=not args.quiet,
    )

    # ── Build and save landscape ──────────────────────────────────────────────
    landscape = build_landscape(results, context=args.context)
    landscape_path = output_dir / "landscape.md"
    landscape_path.write_text(landscape, encoding="utf-8")

    print(f"\n{'═' * 60}")
    print(f"✅ Batch complete")
    print(f"   {len(results)} brief(s) saved to {output_dir}/")
    print(f"   Landscape summary: {landscape_path}")
    print(f"{'═' * 60}\n")


if __name__ == "__main__":
    main()
