"""
Slack Output
------------
Pushes a competitive brief and scorecard to a Slack channel
via an Incoming Webhook.

The Slack message is designed for quick scanning in a busy channel:
- Threat level badge up front
- Dimension scores in a compact table
- Strategic summary as the body
- Link to the full brief

Setup:
    1. Go to api.slack.com/apps → Create New App → From Scratch
    2. Enable "Incoming Webhooks" and add a webhook for your channel
    3. Copy the webhook URL and set: export SLACK_WEBHOOK_URL=https://hooks.slack.com/...

Usage (standalone):
    python outputs/slack_output.py --brief briefs/notion-ai.md --target "Notion AI"

Usage (as a module):
    from outputs.slack_output import send_to_slack
    send_to_slack(scorecard=scorecard, brief_path=Path("briefs/notion-ai.md"))
"""

import argparse
import json
import os
import sys
import urllib.request
import urllib.error
from pathlib import Path

# Add parent dir to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))
from scorer import score_brief, Scorecard, THREAT_EMOJI, THREAT_LEVELS

# ── Slack Block Builder ───────────────────────────────────────────────────────

def build_slack_blocks(scorecard: Scorecard, brief_path: Path = None) -> list[dict]:
    """
    Builds Slack Block Kit blocks for a competitive brief notification.
    Optimised for readability in a #competitive-intel or #product-strategy channel.
    """
    emoji = THREAT_EMOJI.get(scorecard.overall_threat, "⚪")

    # Score bar for text rendering
    def score_bar(s: int) -> str:
        return "█" * s + "░" * (10 - s)

    blocks = [
        # ── Header ────────────────────────────────────────────────────────────
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"{emoji} Competitive Brief: {scorecard.target}",
                "emoji": True,
            },
        },
        # ── Threat level + score ──────────────────────────────────────────────
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Threat Level*\n{emoji} {scorecard.overall_threat}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Composite Score*\n{scorecard.average_score()} / 10",
                },
            ],
        },
        {"type": "divider"},
        # ── Strategic summary ─────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Strategic Read*\n{scorecard.threat_summary}",
            },
        },
        # ── Top risk ──────────────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"⚠️ *Top Risk:* {scorecard.top_risk}",
            },
        },
        {"type": "divider"},
        # ── Dimension scores ──────────────────────────────────────────────────
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Dimension Scores*\n"
                + "\n".join(
                    f"`{score_bar(d.score)}` *{d.score}/10* — {key.replace('_', ' ').title()}"
                    for key, d in scorecard.scores.items()
                ),
            },
        },
    ]

    # ── Optional brief link ───────────────────────────────────────────────────
    if brief_path:
        blocks += [
            {"type": "divider"},
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"📄 Full brief: `{brief_path.name}` · Generated by PM Research Agent",
                    }
                ],
            },
        ]

    return blocks


# ── Send Function ─────────────────────────────────────────────────────────────

def send_to_slack(
    scorecard: Scorecard,
    webhook_url: str = None,
    brief_path: Path = None,
    verbose: bool = True,
) -> bool:
    """
    Sends a competitive brief scorecard to Slack via webhook.
    Returns True on success, False on failure.
    """
    url = webhook_url or os.environ.get("SLACK_WEBHOOK_URL")

    if not url:
        print("❌ No Slack webhook URL found.")
        print("   Set it with: export SLACK_WEBHOOK_URL=https://hooks.slack.com/...")
        return False

    payload = json.dumps({"blocks": build_slack_blocks(scorecard, brief_path)}).encode("utf-8")

    try:
        req = urllib.request.Request(
            url,
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 200:
                if verbose:
                    print(f"✅ Posted to Slack: {scorecard.target} ({scorecard.overall_threat} threat)")
                return True
            else:
                print(f"❌ Slack returned status {resp.status}")
                return False

    except urllib.error.URLError as e:
        print(f"❌ Failed to reach Slack: {e}")
        return False


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Push a competitive brief to Slack"
    )
    parser.add_argument("--brief", required=True, help="Path to brief .md file")
    parser.add_argument("--target", default=None, help="Override target name")
    parser.add_argument("--webhook", default=None, help="Slack webhook URL (overrides env var)")
    parser.add_argument("--dry-run", action="store_true", help="Print blocks JSON without sending")
    args = parser.parse_args()

    brief_path = Path(args.brief)
    if not brief_path.exists():
        print(f"❌ File not found: {brief_path}")
        sys.exit(1)

    target = args.target or brief_path.stem.replace("-", " ").replace("_", " ").title()
    brief_text = brief_path.read_text(encoding="utf-8")

    scorecard = score_brief(target=target, brief_text=brief_text)

    if args.dry_run:
        blocks = build_slack_blocks(scorecard, brief_path)
        print(json.dumps({"blocks": blocks}, indent=2))
        return

    send_to_slack(
        scorecard=scorecard,
        webhook_url=args.webhook,
        brief_path=brief_path,
    )


if __name__ == "__main__":
    main()
